#!/bin/bash
apt install curl apt-transport-https unzip wget libcap2-bin software-properties-common lsb-release gnupg -y
curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | apt-key add -
echo "deb https://packages.wazuh.com/4.x/apt/ stable main" | tee -a /etc/apt/sources.list.d/wazuh.list
apt update -y
apt-get install wazuh-manager -y
